config/routes.rb
Rails.application.routes.draw do

  resources :timetables
  get 'chatrooms/show_chat'
  get 'chatrooms/exit_chat'

  post '/messages' => 'messages#chat_create'
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  get "/eba_answers" => redirect("eba/index")
  get "/eba_questions" => redirect("eba/index")
  mount ActionCable.server => '/cable'
  resources :eba_answers
  resources :eba_questions do
    member do
      get :list
      get :add
    end
  end
  resources :ht_favorites
  resources :ht_routes
  resources :gr_fileserver_contents
  resources :chat_groups
  resources :chat_messages
  resources :rh21_posts
  resources :rh21_threads
  resources :rh21_roles
  resources :rh21_languages
  resources :rh21_statuses
  resources :ik_categories
  resources :ik_memos

  get 'daizu39/index'
  get 'eba/index'
  get 'eba/showall'
  get 'eba/sort'
  get 'eba/search'
  post 'eba/search'
  get 'chat2/index'
  get 'okane/index'

  resources :smpl_chats
  devise_for :users
  resources :users
  get 'guterise_fileserver/index'
  get 'gr_fileserver_content/file_content' => 'gr_fileserver_content#file_content'
  get 'download' => 'gr_fileserver_contents#download', :as => 'download'
  get 'likes' => 'rh21_threads#likes', :as => 'likes'
  get 'dislikes' => 'rh21_threads#dislikes', :as => 'dislikes'

  get 'chat/index'
  post 'chat/index'

  get 'rh21_thread/index'
  get 'ikuo/sample'
  get 'hitme/index'
  get 'hitme/traffic_list'
  get 'ht_routes_list', :to => 'ht_routes#index'
  post 'ht_favorites/create/:id' => 'ht_favorites#create'
  post 'ht_favorites/destroy/:id' => 'ht_favorites#destroy'
  get 'welcome/index'

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat_group.rb
class ChatGroup < ApplicationRecord
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :chat_message
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  has_many :messages
  validates_length_of :name, :maximum => 20
end

app/models/eba_answer.rb
class EbaAnswer < ApplicationRecord
  belongs_to :eba_question
end

app/models/ht_favorite.rb
class HtFavorite < ApplicationRecord
  belongs_to :user 
  belongs_to :ht_route, optional: true
end

app/models/ht_route.rb
class HtRoute < ApplicationRecord
  has_many :ht_favorites
end

app/models/ik_category.rb
class IkCategory < ApplicationRecord
  has_many :ik_memos
end

app/models/ik_memo.rb
class IkMemo < ApplicationRecord
  belongs_to :ik_category
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/rh21_post.rb
class Rh21Post < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :rh21_threads
end

app/models/rh21_role.rb
class Rh21Role < ApplicationRecord
end

app/models/rh21_status.rb
class Rh21Status < ApplicationRecord
end

app/models/rh21_thread.rb
class Rh21Thread < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :rh21_posts, :dependent => :destroy
  validates_presence_of :title
  validates_presence_of :subject
  validates_presence_of :content
  validates_presence_of :language_id
  validates_presence_of :user_id
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user
end

app/models/smpl_chat.rb
class SmplChat < ApplicationRecord
  belongs_to :user
end

app/models/timetable.rb
class Timetable < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :smpl_chats
  has_many :gr_fileserver_contents
  has_many :rh21_posts
  has_many :rh21_threads

  has_many :ht_favorites

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages

end

app/controllers/chat_groups_controller.rb
class ChatGroupsController < ApplicationController
  before_action :set_chat_group, only: [:show, :edit, :update, :destroy]

  # GET /chat_groups
  # GET /chat_groups.json
  def index
    @chat_groups = ChatGroup.all
  end

  # GET /chat_groups/1
  # GET /chat_groups/1.json
  def show
  end

  # GET /chat_groups/new
  def new
    @chat_group = ChatGroup.new
  end

  # GET /chat_groups/1/edit
  def edit
  end

  # POST /chat_groups
  # POST /chat_groups.json
  def create
    @chat_group = ChatGroup.new(chat_group_params)

    respond_to do |format|
      if @chat_group.save
        format.html { redirect_to @chat_group, notice: 'Chat group was successfully created.' }
        format.json { render :show, status: :created, location: @chat_group }
      else
        format.html { render :new }
        format.json { render json: @chat_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_groups/1
  # PATCH/PUT /chat_groups/1.json
  def update
    respond_to do |format|
      if @chat_group.update(chat_group_params)
        format.html { redirect_to @chat_group, notice: 'Chat group was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat_group }
      else
        format.html { render :edit }
        format.json { render json: @chat_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_groups/1
  # DELETE /chat_groups/1.json
  def destroy
    @chat_group.destroy
    respond_to do |format|
      format.html { redirect_to chat_groups_url, notice: 'Chat group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_group
      @chat_group = ChatGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_group_params
      params.require(:chat_group).permit(:name)
    end
end

app/helpers/chat_groups_helper.rb
module ChatGroupsHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/eba_helper.rb
module EbaHelper
end

app/helpers/ikuo_helper.rb
module IkuoHelper
end

app/views/chat_groups/_form.html.erb
<%= form_for(chat_group) do |f| %>
  <% if chat_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat_group.errors.count, "error") %> prohibited this chat_group from being saved:</h2>

      <ul>
      <% chat_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chat_groups/edit.html.erb
<h1>Editing Chat Group</h1>

<%= render 'form', chat_group: @chat_group %>

<%= link_to 'Show', @chat_group %> |
<%= link_to 'Back', chat_groups_path %>

app/views/chat_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chat Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chat_groups.each do |chat_group| %>
      <tr>
        <td><%= chat_group.name %></td>
        <td><%= link_to 'Show', chat_group %></td>
        <td><%= link_to 'Edit', edit_chat_group_path(chat_group) %></td>
        <td><%= link_to 'Destroy', chat_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat Group', new_chat_group_path %>

app/views/chat_groups/new.html.erb
<h1>New Chat Group</h1>

<%= render 'form', chat_group: @chat_group %>

<%= link_to 'Back', chat_groups_path %>

app/views/chat_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chat_group.name %>
</p>

<%= link_to 'Edit', edit_chat_group_path(@chat_group) %> |
<%= link_to 'Back', chat_groups_path %>