config/routes.rb
Rails.application.routes.draw do

  resources :timetables
  get 'chatrooms/show_chat'
  get 'chatrooms/exit_chat'

  post '/messages' => 'messages#chat_create'
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  get "/eba_answers" => redirect("eba/index")
  get "/eba_questions" => redirect("eba/index")
  mount ActionCable.server => '/cable'
  resources :eba_answers
  resources :eba_questions do
    member do
      get :list
      get :add
    end
  end
  resources :ht_favorites
  resources :ht_routes
  resources :gr_fileserver_contents
  resources :chat_groups
  resources :chat_messages
  resources :rh21_posts
  resources :rh21_threads
  resources :rh21_roles
  resources :rh21_languages
  resources :rh21_statuses
  resources :ik_categories
  resources :ik_memos

  get 'daizu39/index'
  get 'eba/index'
  get 'eba/showall'
  get 'eba/sort'
  get 'eba/search'
  post 'eba/search'
  get 'chat2/index'
  get 'okane/index'

  resources :smpl_chats
  devise_for :users
  resources :users
  get 'guterise_fileserver/index'
  get 'gr_fileserver_content/file_content' => 'gr_fileserver_content#file_content'
  get 'download' => 'gr_fileserver_contents#download', :as => 'download'
  get 'likes' => 'rh21_threads#likes', :as => 'likes'
  get 'dislikes' => 'rh21_threads#dislikes', :as => 'dislikes'

  get 'chat/index'
  post 'chat/index'

  get 'rh21_thread/index'
  get 'ikuo/sample'
  get 'hitme/index'
  get 'hitme/traffic_list'
  get 'ht_routes_list', :to => 'ht_routes#index'
  post 'ht_favorites/create/:id' => 'ht_favorites#create'
  post 'ht_favorites/destroy/:id' => 'ht_favorites#destroy'
  get 'welcome/index'

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat_group.rb
class ChatGroup < ApplicationRecord
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  has_many :messages
  validates_length_of :name, :maximum => 20
end

app/models/eba_answer.rb
class EbaAnswer < ApplicationRecord
  belongs_to :eba_question
end

app/models/ht_favorite.rb
class HtFavorite < ApplicationRecord
  belongs_to :user 
  belongs_to :ht_route, optional: true
end

app/models/ht_route.rb
class HtRoute < ApplicationRecord
  has_many :ht_favorites
end

app/models/ik_category.rb
class IkCategory < ApplicationRecord
  has_many :ik_memos
end

app/models/ik_memo.rb
class IkMemo < ApplicationRecord
  belongs_to :ik_category
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/rh21_post.rb
class Rh21Post < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :rh21_threads
end

app/models/rh21_role.rb
class Rh21Role < ApplicationRecord
end

app/models/rh21_status.rb
class Rh21Status < ApplicationRecord
end

app/models/rh21_thread.rb
class Rh21Thread < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :rh21_posts, :dependent => :destroy
  validates_presence_of :title
  validates_presence_of :subject
  validates_presence_of :content
  validates_presence_of :language_id
  validates_presence_of :user_id
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user
end

app/models/smpl_chat.rb
class SmplChat < ApplicationRecord
  belongs_to :user
end

app/models/timetable.rb
class Timetable < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :smpl_chats
  has_many :gr_fileserver_contents
  has_many :rh21_posts
  has_many :rh21_threads

  has_many :ht_favorites

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages

end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :set_timetable, only: [:show, :edit, :update, :destroy]

  # GET /timetables
  # GET /timetables.json
  def index
    @timetables = Timetable.all
  end

  # GET /timetables/1
  # GET /timetables/1.json
  def show
  end

  # GET /timetables/new
  def new
    @timetable = Timetable.new
  end

  # GET /timetables/1/edit
  def edit
  end

  # POST /timetables
  # POST /timetables.json
  def create
    @timetable = Timetable.new(timetable_params)

    respond_to do |format|
      if @timetable.save
        format.html { redirect_to @timetable, notice: 'Timetable was successfully created.' }
        format.json { render :show, status: :created, location: @timetable }
      else
        format.html { render :new }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timetables/1
  # PATCH/PUT /timetables/1.json
  def update
    respond_to do |format|
      if @timetable.update(timetable_params)
        format.html { redirect_to @timetable, notice: 'Timetable was successfully updated.' }
        format.json { render :show, status: :ok, location: @timetable }
      else
        format.html { render :edit }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timetables/1
  # DELETE /timetables/1.json
  def destroy
    @timetable.destroy
    respond_to do |format|
      format.html { redirect_to timetables_url, notice: 'Timetable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetable
      @timetable = Timetable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timetable_params
      params.require(:timetable).permit(:inbound, :route_id, :hour, :min)
    end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/eba_helper.rb
module EbaHelper
end

app/helpers/ikuo_helper.rb
module IkuoHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/views/timetables/_form.html.erb
<%= form_for(timetable) do |f| %>
  <% if timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>

      <ul>
      <% timetable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :inbound %>
    <%= f.number_field :inbound %>
  </div>

  <div class="field">
    <%= f.label :route_id %>
    <%= f.number_field :route_id %>
  </div>

  <div class="field">
    <%= f.label :hour %>
    <%= f.number_field :hour %>
  </div>

  <div class="field">
    <%= f.label :min %>
    <%= f.number_field :min %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timetables/edit.html.erb
<h1>Editing Timetable</h1>

<%= render 'form', timetable: @timetable %>

<%= link_to 'Show', @timetable %> |
<%= link_to 'Back', timetables_path %>

app/views/timetables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Timetables</h1>

<table>
  <thead>
    <tr>
      <th>Inbound</th>
      <th>Route</th>
      <th>Hour</th>
      <th>Min</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timetables.each do |timetable| %>
      <tr>
        <td><%= timetable.inbound %></td>
        <td><%= timetable.route_id %></td>
        <td><%= timetable.hour %></td>
        <td><%= timetable.min %></td>
        <td><%= link_to 'Show', timetable %></td>
        <td><%= link_to 'Edit', edit_timetable_path(timetable) %></td>
        <td><%= link_to 'Destroy', timetable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timetable', new_timetable_path %>

app/views/timetables/new.html.erb
<h1>New Timetable</h1>

<%= render 'form', timetable: @timetable %>

<%= link_to 'Back', timetables_path %>

app/views/timetables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inbound:</strong>
  <%= @timetable.inbound %>
</p>

<p>
  <strong>Route:</strong>
  <%= @timetable.route_id %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @timetable.hour %>
</p>

<p>
  <strong>Min:</strong>
  <%= @timetable.min %>
</p>

<%= link_to 'Edit', edit_timetable_path(@timetable) %> |
<%= link_to 'Back', timetables_path %>