config/routes.rb
Rails.application.routes.draw do

  resources :timetables
  get 'chatrooms/show_chat'
  get 'chatrooms/exit_chat'

  post '/messages' => 'messages#chat_create'
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  get "/eba_answers" => redirect("eba/index")
  get "/eba_questions" => redirect("eba/index")
  mount ActionCable.server => '/cable'
  resources :eba_answers
  resources :eba_questions do
    member do
      get :list
      get :add
    end
  end
  resources :ht_favorites
  resources :ht_routes
  resources :gr_fileserver_contents
  resources :chat_groups
  resources :chat_messages
  resources :rh21_posts
  resources :rh21_threads
  resources :rh21_roles
  resources :rh21_languages
  resources :rh21_statuses
  resources :ik_categories
  resources :ik_memos

  get 'daizu39/index'
  get 'eba/index'
  get 'eba/showall'
  get 'eba/sort'
  get 'eba/search'
  post 'eba/search'
  get 'chat2/index'
  get 'okane/index'

  resources :smpl_chats
  devise_for :users
  resources :users
  get 'guterise_fileserver/index'
  get 'gr_fileserver_content/file_content' => 'gr_fileserver_content#file_content'
  get 'download' => 'gr_fileserver_contents#download', :as => 'download'
  get 'likes' => 'rh21_threads#likes', :as => 'likes'
  get 'dislikes' => 'rh21_threads#dislikes', :as => 'dislikes'

  get 'chat/index'
  post 'chat/index'

  get 'rh21_thread/index'
  get 'ikuo/sample'
  get 'hitme/index'
  get 'hitme/traffic_list'
  get 'ht_routes_list', :to => 'ht_routes#index'
  post 'ht_favorites/create/:id' => 'ht_favorites#create'
  post 'ht_favorites/destroy/:id' => 'ht_favorites#destroy'
  get 'welcome/index'

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat_group.rb
class ChatGroup < ApplicationRecord
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  has_many :messages
  validates_length_of :name, :maximum => 20
end

app/models/eba_answer.rb
class EbaAnswer < ApplicationRecord
  belongs_to :eba_question
end

app/models/ht_favorite.rb
class HtFavorite < ApplicationRecord
  belongs_to :user 
  belongs_to :ht_route, optional: true
end

app/models/ht_route.rb
class HtRoute < ApplicationRecord
  has_many :ht_favorites
end

app/models/ik_category.rb
class IkCategory < ApplicationRecord
  has_many :ik_memos
end

app/models/ik_memo.rb
class IkMemo < ApplicationRecord
  belongs_to :ik_category
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/rh21_post.rb
class Rh21Post < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :rh21_threads
end

app/models/rh21_role.rb
class Rh21Role < ApplicationRecord
end

app/models/rh21_status.rb
class Rh21Status < ApplicationRecord
end

app/models/rh21_thread.rb
class Rh21Thread < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :rh21_posts, :dependent => :destroy
  validates_presence_of :title
  validates_presence_of :subject
  validates_presence_of :content
  validates_presence_of :language_id
  validates_presence_of :user_id
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user
end

app/models/smpl_chat.rb
class SmplChat < ApplicationRecord
  belongs_to :user
end

app/models/timetable.rb
class Timetable < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :smpl_chats
  has_many :gr_fileserver_contents
  has_many :rh21_posts
  has_many :rh21_threads

  has_many :ht_favorites

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages

end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/eba_helper.rb
module EbaHelper
end

app/helpers/ikuo_helper.rb
module IkuoHelper
end

app/views/shared/_chat_room.html.erb
<ul class="list-group" style="text-align:center;">
  <% if user_signed_in? %>
    <% if session['chat_on'] %>
      <h2><%= session['chat_title'] %></h4>
      <% @messages = session[:chat_message] %>
      <% @chatroom_id = session[:chat_on] %>

      <div data-behavior='messages' data-chatroom-id='<%= @chatroom_id %>' >
        <% @messages.each do |message| %>
          <% m = Message.new(message) %>
          <% if !m.user.handle.nil? %>
            <%= m.user.handle %>:<%= m.body %><br />
          <% elsif m.body %>
            No Name: <%= m.body %><br />
          <% end %>
        <% end %>
        <%= form_tag('/messages', method: 'post', :id=>'rc_body_form' ) do %>
          <input type="hidden" name="chatroom_id", value="<%= @chatroom_id %>" />
          <input type="hidden" name="goback_to", value='<%= request.original_url%>' />
          <%= text_area_tag "body", "", rows: 1, class: "form-control", autofocus: true,
              :id => "rc_body" %>
        <% end %>
      </div>

      <script type="text/javascript">
        // This script should come after the id is defined.
        document.getElementById('rc_body').onkeypress =
          function(e){
            if ( e && (e.keyCode == 13) )
            {
              e.preventDefault();
              document.getElementById('rc_body_form').submit()
            }
          };
      </script>


      <%= link_to "Exit Chat", chatrooms_exit_chat_path( goback_to: request.original_url ) %>
    <% else %>
      <% current_user.chatrooms.each do |chatroom| %>
        <li class="list-group-item" style="margin:10px;">
          <%= link_to chatroom.name, chatrooms_show_chat_path(
            chatroom_id: chatroom.id, goback_to: request.original_url
          ) %>
          <!--  link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} -->
        </li>
      <% end%>
      <%= link_to 'See all chat rooms', chatrooms_path, class: 'btn btn-default btn-success' %>
      <hr/>
      <%= link_to 'Create New Chatroom', new_chatroom_path, class: 'btn btn-default' %>
    <% end %>
  <% end %>
</ul>

app/views/shared/_file_server.html.erb
Hello, I am in File Server sub page.
<br />
<%= link_to 'Go to fileserver', gr_fileserver_contents_path %>

app/views/shared/_footer.html.erb
Copyright (C) 2017, by Web+DB Hosei Project Team

app/views/shared/_menu_bar.html.erb
<%= render :partial => "shared/navbar" %>
<% menu_items = [
  { :link => root_path, :name => 'Top Page' },
  { :link => chat_index_path, :name => 'Chat Sample' },
  { :link => 'https://www.ruby-lang.org/en/', :name => 'ruby Official Site' },
  ] -%>
<%
  if current_user.present?
    menu_items.push( {:link => destroy_user_session_path,
        :name=>'Sign Out', :method=>'delete'})
  end
%>
<div class="btn-group">
  <% menu_items.each_with_index do | item, index | -%>
    <div class="btn btn-default">
        <%= menu_link_to item -%>
    </div>
  <% end -%>
</div>

app/views/shared/_nav_bar.html.erb
<div class="navbar-fixed">
  <nav role="navigation">
    <div class="nav-wrapper white-text">
      <%= image_tag "White_face_Scops_Owl_circle.png", :size => "60x60" %>&nbsp;&nbsp;&nbsp;
      <%= link_to "Scops Owl Project", root_path, class: "brand-logo" %>
      <a href="#" id="sidenav" data-activates="slide-out" data-turbolinks="false" class="button-collapse show-on-large"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "Home", root_path, class: "waves-efect waves-light" %></li>
        <li><%= link_to "Chat", okane_index_path, class: "waves-efect waves-light" %></li>
        <li><%= link_to "Fileserver", gr_fileserver_contents_path, class: "waves-efect waves-light" %></li>
        <li><%= link_to "Bus dely", hitme_index_path, class: "waves-efect waves-light" %></li>
      </ul>
    </div>
  </nav>
</div>

<ul id="slide-out" class="side-nav" style="overflow: auto">
  <% if user_signed_in? %>
    <li><div class="userView">
      <div class="background">
        <%= image_tag "Hosei_logo.png" %>
      </div><br />
      <span><%= image_tag "UserFace.png", class: "circle" %></span>
      <span class="name"><%= current_user.handle %></span>
      <span class="email"><%= current_user.email %></span>
    </div></li>
    <li>
      <%= link_to root_path, class: "waves-efect" do %>
        <i class="material-icons">home</i>Home
      <% end %>
    </li>
    <li>
      <%= link_to okane_index_path, class: "waves-efect waves-light" do %>
        <i class="material-icons">chat</i>Chat
      <% end %>
    </li>
    <li>
      <%= link_to gr_fileserver_contents_path, class: "waves-efect waves-ligh" do %>
        <i class="material-icons">cloud</i>Fileserver
      <% end %>
    </li>
    <li>
      <%= link_to hitme_index_path, class: "waves-efect waves-light" do %>
        <i class="material-icons">directions_bus</i>Bus Delay
      <% end %>
    </li>
    <li>
      <%= link_to daizu39_index_path, class: "waves-efect waves-light" do %>
        <i class="material-icons">school</i>Educational support
      <% end %>
    </li>
    <li>
      <%= link_to rh21_threads_path, class: "waves-efect waves-light" do %>
        <i class="material-icons">translate</i>Translation quality
      <% end %>
    </li>
    <li>
      <%= link_to eba_index_path, class: "waves-efect waves-light" do %>
        <i class="material-icons">pages</i>Educational question
      <% end %>
    </li>

    <li><div class="divider"></div></li>
    <li>
      <%= link_to destroy_user_session_path, :method=>'delete' do %>
        <i class="material-icons">exit_to_app</i>Log out
      <% end %>
    </li>

  <% else %>
    <li><%= link_to "Log in", new_user_session_path, class: "waves-efect" %></li>
  <% end %>
</ul>

app/views/shared/_page_footer.html.erb
<!--footer class="page-footer indigo darken-4"-->
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Scops Owl Project</h5>
        <p class="grey-text text-lighten-4">Thank you for using this project.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="https://www.ruby-lang.org/en/">Ruby official site</a></li>
          <li><a class="grey-text text-lighten-3" href="https://www.hosei.ac.jp/">Hosei univiersity</a></li>
          <li><%= link_to "Home", root_path,  class: "grey-text text-lighten-3"%></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      Copyright (C) 2017, by Web+DB Hosei Project Team
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
<!--/footer-->

app/views/shared/_right_bar.html.erb
<h3>links</h3>
<%= link_to "TOP", root_path %><br />
<%= link_to "Chat Sample", chat_index_path %><br />
<%= link_to (t '.lecturers'), ikuo_sample_path %><br />
<hr />
AD space for RENT
<hr />
<h3>Chat Room</h3>
<%= render :partial => "shared/chat_room" %>
<hr />
<h3>File Server</h3>
<%= render :partial => "shared/file_server" %>

app/views/shared/_scrollSpy.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="col s12">
      <ul class="tabs tabs-fixed-width">
        <li class="tab col s6"><a href="#Chat">
            <i class="material-icons">chat</i>Chat Room
         </a>
        </li>
        <li class="tab col s6"><a href="#Fileserver">
            <i class="material-icons">cloud</i>File Server
          </a>
        </li>
      </ul>
    </div>
    <div id="Chat" class="col s12">
      <%= render :partial => "shared/chat_room" %>
    </div>
    <div id="Fileserver" class="col s12">
      <%= render :partial => "shared/file_server" %>
    </div>
  </div>
<% end %>