config/routes.rb
Rails.application.routes.draw do

  resources :timetables
  get 'chatrooms/show_chat'
  get 'chatrooms/exit_chat'

  post '/messages' => 'messages#chat_create'
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  get "/eba_answers" => redirect("eba/index")
  get "/eba_questions" => redirect("eba/index")
  mount ActionCable.server => '/cable'
  resources :eba_answers
  resources :eba_questions do
    member do
      get :list
      get :add
    end
  end
  resources :ht_favorites
  resources :ht_routes
  resources :gr_fileserver_contents
  resources :chat_groups
  resources :chat_messages
  resources :rh21_posts
  resources :rh21_threads
  resources :rh21_roles
  resources :rh21_languages
  resources :rh21_statuses
  resources :ik_categories
  resources :ik_memos

  get 'daizu39/index'
  get 'eba/index'
  get 'eba/showall'
  get 'eba/sort'
  get 'eba/search'
  post 'eba/search'
  get 'chat2/index'
  get 'okane/index'

  resources :smpl_chats
  devise_for :users
  resources :users
  get 'guterise_fileserver/index'
  get 'gr_fileserver_content/file_content' => 'gr_fileserver_content#file_content'
  get 'download' => 'gr_fileserver_contents#download', :as => 'download'
  get 'likes' => 'rh21_threads#likes', :as => 'likes'
  get 'dislikes' => 'rh21_threads#dislikes', :as => 'dislikes'

  get 'chat/index'
  post 'chat/index'

  get 'rh21_thread/index'
  get 'ikuo/sample'
  get 'hitme/index'
  get 'hitme/traffic_list'
  get 'ht_routes_list', :to => 'ht_routes#index'
  post 'ht_favorites/create/:id' => 'ht_favorites#create'
  post 'ht_favorites/destroy/:id' => 'ht_favorites#destroy'
  get 'welcome/index'

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat_group.rb
class ChatGroup < ApplicationRecord
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  has_many :messages
  validates_length_of :name, :maximum => 20
end

app/models/eba_answer.rb
class EbaAnswer < ApplicationRecord
  belongs_to :eba_question
end

app/models/ht_favorite.rb
class HtFavorite < ApplicationRecord
  belongs_to :user 
  belongs_to :ht_route, optional: true
end

app/models/ht_route.rb
class HtRoute < ApplicationRecord
  has_many :ht_favorites
end

app/models/ik_category.rb
class IkCategory < ApplicationRecord
  has_many :ik_memos
end

app/models/ik_memo.rb
class IkMemo < ApplicationRecord
  belongs_to :ik_category
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/rh21_post.rb
class Rh21Post < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :rh21_threads
end

app/models/rh21_role.rb
class Rh21Role < ApplicationRecord
end

app/models/rh21_status.rb
class Rh21Status < ApplicationRecord
end

app/models/rh21_thread.rb
class Rh21Thread < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :rh21_posts, :dependent => :destroy
  validates_presence_of :title
  validates_presence_of :subject
  validates_presence_of :content
  validates_presence_of :language_id
  validates_presence_of :user_id
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user
end

app/models/smpl_chat.rb
class SmplChat < ApplicationRecord
  belongs_to :user
end

app/models/timetable.rb
class Timetable < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :smpl_chats
  has_many :gr_fileserver_contents
  has_many :rh21_posts
  has_many :rh21_threads

  has_many :ht_favorites

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # When the user Handle is not set, force to register Handle
    if current_user.handle.blank?
      url = root_url( only_path: false )
      SignupMailer.signup_email( current_user, url ).deliver_now
      session[:set_handle_from_chat] = true
      redirect_to edit_user_path(current_user)
    end
    session[:user] = current_user

  end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/eba_helper.rb
module EbaHelper
end

app/helpers/ikuo_helper.rb
module IkuoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% if false %>
<h1>Scops Owl Project</h1>
This project is a tryout to develop the Ruby on Rails project,
for Hosei University's Web+DB lecture session. <br />
<h3> Lecture: "Web System Development by Ruby language." </h3>

This year, we aims to install "Chat", and "DropBox" helpers to apply to <br />
the "solution sharing" among the students,<br />
"Bus Delay" information <br />
and Chat web site, <br />
and the "search solution" portal <br />
for the "solution sharing" database.<br />

The folowing is the Jump index to each students Portal views
<h2><%= t 'app.entrance' %></h2>
<ul>
  <li><%= link_to (t '.lecturers'), ikuo_sample_path %></li>
  <li><%= link_to "Chat Sample", chat_index_path %></li>
  <li><%= link_to "Daizu39 portal", daizu39_index_path %></li>
  <li><%= link_to "eba's portal", eba_index_path %></li>
  <li><%= link_to (t 'Gutereise_fileserver'), guterise_fileserver_index_path %></li>
  <li><%= link_to "hitme's portal", hitme_index_path %></li>
  <li><%= link_to "okane's portal", chatrooms_path %></li>
  <li><%= link_to (t '.rh21_thread'), rh21_threads_path %></li>
</ul>
<% end %>

<div class="row">
  <div class="col s12">
    <div class="card grey darken-2">
      <div class="card-image">
        <%= image_tag "banner1.gif" %>
      </div>
      <div class="card-content white-text">
        <p class="flow-text">This project is a tryout to develop the Ruby on Rails project, for Hosei University's Web+DB lecture session.</p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s12 m6">
    <div class="card-panel blue-grey lighten-2">
      <div class="card-content">
        <h2>Lecture: "Web System Development by Ruby langage."</h2>
        <p class="flow-text">This year, we aims to install "Chat", and "DropBox" helpers to apply to the "solution sharing" among the students, "Bus Delay" information and Chat web site, and the "search solution" portal for the "solution sharing" database.</p>
      </div>
    </div>
  </div>
  <div class="col s12 m6">
    <div class="card hoverable grey lighten-2">
      <div class="card-content">
        <span class="card-title"><%= t 'app.entrance' %></span>
        <div class="card-action">
          <ul>
            <li><%= link_to (t '.lecturers'), ikuo_sample_path, class: "orange-text text-accent-4"%></li>
            <li><%= link_to "Chat Sample", chat_index_path, class: "orange-text text-accent-4" %></li>
            <li><%= link_to "Daizu39 portal", daizu39_index_path, class: "orange-text text-accent-4" %></li>
            <li><%= link_to "eba's portal", eba_index_path, class: "orange-text text-accent-4" %></li>
            <li><%= link_to (t 'Gutereise_fileserver'), guterise_fileserver_index_path, class: "orange-text text-accent-4" %></li>
            <li><%= link_to "hitme's portal", hitme_index_path, class: "orange-text text-accent-4" %></li>
            <li><%= link_to "okane's portal", chatrooms_path, class: "orange-text text-accent-4" %></li>
            <li><%= link_to (t '.rh21_thread'), rh21_threads_path, class: "orange-text text-accent-4" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>